#!/usr/bin/env python3
"""Turn figure JSON into something pgfplots can read.

Every figure in this directory is three files with the same stem:

    fig-m1-value-cdf.tex     the drawing code   (hand-written, no numbers)
    fig-m1-value-cdf.json    the data           (numbers only, no layout)
    fig-m1-value-cdf.pdf     the compiled figure

LaTeX cannot read JSON, so this script is the bridge.  For each .json it
writes a scratch directory

    .build/<stem>/data.tex     scalars, labels, generated heatmap cells
    .build/<stem>/<series>.dat one whitespace-separated table per series

which figures/preamble.tex pulls in automatically using \\jobname.  Nothing in
.build/ is edited by hand and nothing in it is committed.

Schema (all blocks optional except "meta"):

  meta      id / kind / title / source / placeholder / notes.  Documentation
            only for `kind: schematic` figures, which carry no data.
  scalars   name -> number quoted in the figure.  Reachable as \\figval{name}.
  labels    name -> legend text (may contain LaTeX).  \\figlabel{name}.
  series    name -> {columns: [...], rows: [[...], ...]} -> <name>.dat
  grids     name -> heatmap; see emit_grid below.

Usage:  python3 build.py [--check]
        --check exits non-zero if any .build output is stale or missing.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
BUILD = HERE / ".build"
SOURCE_DIRS = ("experiment", "schematic")


def fmt(x) -> str:
    """Render a JSON scalar the way TeX wants to see it."""
    if isinstance(x, bool):
        return "true" if x else "false"
    if isinstance(x, float):
        # Trailing zeros in a .dat are harmless but make diffs noisy.
        s = f"{x:.10g}"
        return s
    return str(x)


def emit_series(out: Path, name: str, spec: dict) -> None:
    """One series -> one whitespace-separated table with a named header.

    Column names become the keys used in `\\addplot table[x=..., y=...]`, so
    keep them short and alphanumeric.  Symbolic x coordinates (bar charts)
    are just string cells; pgfplots reads them fine.
    """
    cols = spec["columns"]
    rows = spec["rows"]
    for i, row in enumerate(rows):
        if len(row) != len(cols):
            raise SystemExit(
                f"{name}: row {i} has {len(row)} values but {len(cols)} columns"
            )
    lines = [" ".join(cols)]
    lines += [" ".join(fmt(v) for v in row) for row in rows]
    (out / f"{name}.dat").write_text("\n".join(lines) + "\n")


def emit_grid(name: str, spec: dict) -> list[str]:
    """A heatmap -> generated \\heatcell calls plus its two tick lists.

    Cell colour intensity is a pure function of the cell value:

        intensity = min(100, 100 * (v / vmax) ** gamma)

    This is the property that makes panels comparable, and it is exactly the
    thing that rots when cells are written by hand -- swap in real numbers and
    the old hand-computed intensities silently stop meaning anything.  So the
    JSON stores only the values and the two parameters, and the intensities
    are recomputed here on every build.
    """
    values = spec["values"]          # values[row][col], row 0 at the bottom
    vmax = spec["intensity"]["vmax"]
    gamma = spec["intensity"]["gamma"]
    precision = spec.get("precision", 1)

    cells = []
    for r, row in enumerate(values):
        line = []
        for c, v in enumerate(row):
            intensity = min(100.0, 100.0 * (v / vmax) ** gamma)
            line.append(f"\\heatcell{{{c}}}{{{r}}}{{{round(intensity)}}}"
                        f"{{{v:.{precision}f}}}")
        cells.append("  " + " ".join(line))

    def ticklist(items):
        return ",".join(f"{i}/{{{lab}}}" for i, lab in enumerate(items))

    body = "%\n".join(cells)
    return [
        f"\\figgriddef{{{name}}}{{%\n{body}}}",
        f"\\figgridcolsdef{{{name}}}{{{ticklist(spec['collabels'])}}}",
        f"\\figgridrowsdef{{{name}}}{{{ticklist(spec['rowlabels'])}}}",
    ]


def build_one(src: Path) -> Path:
    spec = json.loads(src.read_text())
    stem = src.stem
    out = BUILD / stem
    out.mkdir(parents=True, exist_ok=True)

    meta = spec.get("meta", {})
    lines = [
        "%% GENERATED by figures/build.py from "
        f"{src.parent.name}/{src.name} -- do not edit.",
        f"%% {meta.get('title', '')}",
    ]
    if meta.get("placeholder"):
        lines.append("%% NOTE: these numbers are placeholders. "
                     "See PLACEHOLDERS.md.")
    if meta.get("source"):
        lines.append(f"%% source: {meta['source']}")

    for name, value in spec.get("scalars", {}).items():
        lines.append(f"\\figvaldef{{{name}}}{{{fmt(value)}}}")
    for name, text in spec.get("labels", {}).items():
        lines.append(f"\\figlabeldef{{{name}}}{{{text}}}")
    for name, grid in spec.get("grids", {}).items():
        lines.extend(emit_grid(name, grid))
    for name, series in spec.get("series", {}).items():
        emit_series(out, name, series)

    (out / "data.tex").write_text("\n".join(lines) + "\n")
    return out


def sources() -> list[Path]:
    found = []
    for d in SOURCE_DIRS:
        found.extend(sorted((HERE / d).glob("*.json")))
    return found


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="fail if any generated file is missing or stale")
    args = ap.parse_args()

    srcs = sources()
    if not srcs:
        print("no figure JSON found", file=sys.stderr)
        return 1

    if args.check:
        bad = []
        for s in srcs:
            out = BUILD / s.stem / "data.tex"
            if not out.exists():
                bad.append(("not built", s))
            elif out.stat().st_mtime < s.stat().st_mtime:
                bad.append(("stale", s))
        for why, s in bad:
            print(f"{why}: {s.relative_to(HERE)}", file=sys.stderr)
        if bad and all(why == "not built" for why, _ in bad):
            print("nothing has been built yet (or `make clean` removed it); "
                  "run `make`", file=sys.stderr)
        return 1 if bad else 0

    for s in srcs:
        build_one(s)
    print(f"build.py: generated data for {len(srcs)} figures")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
